---
# Pipelines use "resources" to interact with the outside world.
# There are a number of built-in resources, and Concourse can
# be extended by adding additional resource types.

# We need to fetch files from PivNet, so need to add a resource
# type that can interact with it.
#
# This pipeline uses that resource to fetch a file from PivNet to
# validate access.
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: opsman-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token)) # This inserts the value of a 'pivnet_token' variable
    product_slug: ops-manager
    product_version: 2\.5\.(.*) # Selects the latest release of the v2.5 series
    sort_by: semver

jobs:
- name: fetch-opsman
  plan:
  - get: opsman-pivnet
    trigger: true
    params:
      globs:
      - "*onGCP.yml"
